### ISSUE TITLE
Event not being saved to Google Calendar with `createEvent` function on Android

### ISSUE THREAD

**Issue by scaabel** [ebarooni/capacitor-calendar#137] opened 2024-09-19 03:37 UTC
Hi, thanks for making such a great package.

I'm on an Android emulator (Google Pixel 3A) and the default calendar app is Google Calendar. I'm facing an issue where the events that I'm trying to save are not actually being added to Google Calendar. The feature I'm building allows users to select multiple events to be synced to their calendar.

I think the issue is caused by the available calendars in when `CapacitorCalendar.listCalendars()` is called. I'm only getting the `Holidays` and `Birthdays` calendar in the list and both of these calendars are possibly read only. Here is the log of the list

`list of calendars [{"id":"1","title":"Holidays in United States","color":"#16A765"},{"id":"2","title":"Birthdays","color":"#92E1C0"}]`.

Below is the implementation to handle the creation of events. There are no errors thrown except when I try to omit the `calendarId`.

```typescript
const response = await Promise.allSettled(
      events.map((event: CalendarEvent) => {
        const eventParams = {
          calendarId,
          title: event.title,
          notes: event.notes,
          startDate: event.startDate,
          endDate: event.endDate,
          isAllDay: false,
          alertOffsetInMinutes: event?.alertOffsetInMinutes ?? [30, 1]
        }

        console.log('eventParams', JSON.stringify(eventParams))
        return CapacitorCalendar.createEvent(eventParams).catch((error) => {
          console.log(
            'error',
            JSON.stringify({
              title: event.title,
              error
            })
          )
          throw {
            title: event.title,
            error: error.message
          } as FailedEvent
        })
      })
    )
    
    console.log('response', JSON.stringify(response))
```

capacitor-calendar version: ^6.7.0
@capacitor/core version: ^5.7.3

Do let me know if there is something wrong with my implementation or if you require further information.

Thanks again for such an amazing package!

**Comment by ebarooni** [comment] 2024-09-20 07:15
Hey @scaabel  and thanks. My assumption is that on the emulator you are not signed in with any google account. And thats why `listCalendars` returns only the birthdays and holidays. These calendars are readonly and therefore cant be manipulated. 

Your implementation seems to be correct but to be sure I would try just a basic event only with a title to see if everything works as expected. 

What i would try is to login with a google account and the emulator (if you havent already) and to see if you have access to your own calendar and if you can add events to it using the method. 

If this still didnt work:

- Is the android version of the emulator compatible with the minimum supported version of the plugin?
- Are the necessary permissions In your manifest file present? Also did you request write access?

What i can offer is to implement a way to know if a calendar is readonly or not (this is already supported on ios). And like this you can filter out the calendars that are readonly. 

I noticed your capacitor core version is 5.x.x but you are using the plugin for version 6.x.x. Doesnt this create issues? My expectation is that these major version of these dependencies should always match.

**Comment by scaabel** [comment] 2024-09-23 06:34
Hi @ebarooni, thanks for the prompt reply.

I've ensured that the emulator has logged in with a proper google account. I've also tried with the demo app provided and it is not working as expected even with the correct versions.

Yes, permissions were requested. The `createEvent` function works fine in my iOS app. This only happens in Android devices.

**Comment by ebarooni** [comment] 2024-09-23 09:08
@scaabel I will test this behavior and get back to you here.

**Comment by scaabel** [comment] 2024-09-24 06:14
@ebarooni thanks, really appreciate it.

**Comment by ebarooni** [comment] 2024-09-25 19:30
Hi @scaabel , i tested the behaviors that you reported. However i was not able to reproduce any! For the tests i used the example app from the repo without any modifications. `listCalendars` returned all my available calendars and `createEvent` saved an event to my personal calendar (both android). For `listCalendars` i request first read access and then i invoked the method. The available calendars on my emulator according to the calendar app itself is the following:

![Screenshot_20240925_211234](https://github.com/user-attachments/assets/e4da7eb6-484d-400a-84fb-b38a95f0198d)

And i received all from the plugin as expected. And for creating an event, first i requested write access and then i invoked the method from the example app.

Can you maybe give me more info on your setup? Which framework? What version? What model is the emulator and which android version?

My emulator is a Pixel 7 Pro with API level 34.

**Comment by ebarooni** [comment] 2024-09-26 07:08
@scaabel And also what do you get when you invoke `getDefaultCalendar`?

**Comment by scaabel** [comment] 2024-09-27 00:38
Hi @ebarooni , 

I'm using react/nextjs alongside this package.

Here is my emulator setup:
Pixel 3A, API 34

I've attached a screenshot based on the demo app.

Here are the results of the function invoked rom the bottom to top:
1. `listCalendars`
2. `getDefaultCalendar`
3. `createEvent`

I hope this information helps.

![capacitor-calendar-errors](https://github.com/user-attachments/assets/85f2d1be-61bb-43ee-a9d8-e0a6ce76be37)

**Comment by AhegaHOE** [comment] 2024-09-27 12:27
Hi @scaabel,

If you omitted the `calendarId` and no calendar is marked as [`IS_PRIMARY`](https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns#IS_PRIMARY), which is indicated by `getDefaultCalendar` returning an empty object, then this behavior is expected. I recommend always providing a `calendarId`.

**Comment by ebarooni** [comment] 2024-09-27 12:55
@AhegaHOE his issue is that `listCalendars` also does not return all available calendars. But now im not so sure why is this happening.

**Comment by AhegaHOE** [comment] 2024-09-27 13:27
@ebarooni hmm that is odd. I have tested it myself with my personal account and it shows all my calendars... 🤔

**Comment by AhegaHOE** [comment] 2024-09-27 13:31
@scaabel could you make create a sample project with instructions on how reproduce this? I could also not reproduce it, just like @ebarooni .

**Comment by scaabel** [comment] 2024-10-09 23:12
@AhegaHOE for the repro, you can try using the demo app provided. I'll try to provide a repro once I'm available.

Do you think there are different settings that needs to be set within Google Calendar itself?

**Comment by AhegaHOE** [comment] 2024-10-09 23:23
Hi @scaabel, I have used the demo app for testing and added my personal Google Account in the emulator's Google Calendar App. All Calendars showed up as expected.

I don't think that it is related to the Calendar App itself because it is barely a wrapper for the underlying calendar structure.

Could it be that those Calendars that seem to be missing are added via a different app? I really have no clue why this happens to you therefore please try to create some kind of fresh project that can reproduce this bug.

**Comment by ebarooni** [comment] 2024-11-14 19:30
Closing this issue as it cant be reproduced.

**Closed by ebarooni** 2024-11-14 19:30 UTC
Labels: bug
